version: '3.8'

services:
  frontend:
    build: ./Front  # make sure this path points to your updated Dockerfile
    ports:
      - '80:80'  # changed to map port 80 (Nginx) to 3000 on the host
    container_name: pelekas_frontend
    depends_on:
      - backend

  backend:
    build: ./Back
    ports:
      - '5000:5000'
    container_name: pelekas_backend
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pelekas
    ports:
      - '5432:5432'
    container_name: pelekas_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: