version: '3.8'

services:
  db:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: pelekas
      ports:
        - '5432:5432'
      container_name: pelekas_postgres
      volumes:
        - .db:/var/lib/postgresql/

