version: '3.8'

services:
  frontend:
    build: ./Front
    ports:
      - '3000:3000'
    container_name: pelekas_frontend
    depends_on:
      - backend

  backend:
    build: ./Back
    ports:
      - '5000:5000'
    container_name: pelekas_backend
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pelekas
    ports:
      - '5432:5432'
    container_name: pelekas_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: